# Generate a Windows resource (.rc) file that embeds workshop_sync_tool.exe
# and steam_api64.dll as RCDATA resources inside cloud_redirect.dll.
#
# Called from CMakeLists.txt via add_custom_command with:
#   -DTOOL_EXE=<path to built workshop_sync_tool.exe>
#   -DDLL_FILE=<path to steam_api64.dll>
#   -DOUTPUT=<path to write the .rc file>

if(NOT DEFINED TOOL_EXE OR NOT DEFINED DLL_FILE OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "TOOL_EXE, DLL_FILE, and OUTPUT must be defined")
endif()

# Normalize paths for the RC compiler: use forward slashes and ensure
# the files exist at generation time (workshop_sync_tool must have been
# built already via add_dependencies).
if(NOT EXISTS "${TOOL_EXE}")
    message(FATAL_ERROR "workshop_sync_tool.exe not found at: ${TOOL_EXE}")
endif()
if(NOT EXISTS "${DLL_FILE}")
    message(FATAL_ERROR "steam_api64.dll not found at: ${DLL_FILE}")
endif()

# RC compiler accepts both / and \; use \ for maximum compatibility.
string(REPLACE "/" "\\" TOOL_EXE_RC "${TOOL_EXE}")
string(REPLACE "/" "\\" DLL_FILE_RC "${DLL_FILE}")

set(RC_CONTENT
"#include <windows.h>\n"
"// Auto-generated by cmake/generate_embedded_rc.cmake - do not edit.\n"
"// Embeds workshop_sync_tool.exe and steam_api64.dll so the DLL can\n"
"// extract them to %APPDATA%\\CloudRedirect\\tools at runtime.\n"
"WORKSHOP_TOOL_EXE RCDATA \"${TOOL_EXE_RC}\"\n"
"STEAM_API64_DLL RCDATA \"${DLL_FILE_RC}\"\n"
)

file(WRITE "${OUTPUT}" ${RC_CONTENT})
message(STATUS "Generated embedded resources RC: ${OUTPUT}")